name: Bug Report
description: File a bug report
title: "[Bug]: (TITLE)"
labels: [bug]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: OS
      description: What OS are you running?
      options:
        - Windows
        - MacOS
        - Linux
    validations:
      required: true
  - type: textarea
    id: os-version
    attributes:
      label: OS version
      description: Put the version of your operating system here.
      placeholder: Ubuntu 20.04 LTS
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What version are you seeing the problem on?
      multiple: true
      options:
        - Git
        - Automatic Build
        - Release
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
